services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    command:
      - "mongod"
      - "--bind_ip_all"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
